//go:build ignore

package main

import (
	"fmt"
	"image"
	_ "image/png"
	"os"
)

func main() {
	f, err := os.Open("gopher32.png")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	img, _, err := image.Decode(f)
	if err != nil {
		panic(err)
	}

	b := img.Bounds()
	w, h := b.Max.X, b.Max.Y

	fmt.Println("// Code generated by gen_gopher.go; DO NOT EDIT.")
	fmt.Println("package main")
	fmt.Println()
	fmt.Println(`import "unsafe"`)
	fmt.Println()
	fmt.Printf("const gopherW, gopherH int16 = %d, %d\n", w, h)
	fmt.Println()
	fmt.Printf("const gopherRaw = \"")
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			r, g, b, a := img.At(x, y).RGBA()
			// alpha が薄い箇所は白として扱う
			var rgb565 uint16
			if a < 0x8000 {
				rgb565 = 0xFFFF
			} else {
				rgb565 = uint16(((r>>8)&0xF8)<<8 | ((g>>8)&0xFC)<<3 | (b>>8)>>3)
			}
			// little-endian で2バイト出力
			fmt.Printf("\\x%02X\\x%02X", rgb565&0xFF, rgb565>>8)
		}
	}
	fmt.Println("\"")
	fmt.Println()
	fmt.Println("var gopherBitmap = unsafe.Slice(")
	fmt.Println("\t(*uint16)(unsafe.Pointer(unsafe.StringData(gopherRaw))),")
	fmt.Printf("\tgopherW*gopherH,\n")
	fmt.Println(")")
}
