// Code generated by gen qr; DO NOT EDIT.
package main

var qrBitmapTechnicalPROnX = [33][33]bool{
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,false,false,false,false,true,true,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,false,true,true,false,false,false,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,false,false,true,false,false,false,false,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,true,false,true,true,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,true,false,true,true,true,true,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,true,true,false,false,true,true,false,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,false,false,true,true,true,false,false,false,true,false,true,false,false,false,false,false,false,true,false,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,false,true,false,false,false,false,false,true,false,true,true,false,false,true,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,false,true,true,false,false,true,true,false,false,true,true,true,false,false,true,false,false,true,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,false,true,false,false,true,false,true,false,false,true,false,false,false,true,true,true,false,true,false,true,true,false,false,false,false,false,},
	{false,false,false,false,false,true,false,false,false,true,true,true,true,false,false,true,true,false,false,true,false,true,true,false,false,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,false,false,false,false,false,false,true,true,false,true,false,true,true,true,false,false,false,true,false,false,true,false,false,false,false,false,},
	{false,false,false,false,false,false,true,true,false,false,true,false,true,true,false,true,true,false,false,true,false,true,false,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,true,true,false,false,true,true,false,false,false,false,true,false,false,false,true,true,true,false,true,true,false,false,false,false,false,},
	{false,false,false,false,true,true,false,true,true,true,true,false,true,false,true,false,false,true,false,true,true,true,true,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,true,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,false,true,true,true,false,true,true,false,true,false,true,false,true,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,false,false,true,false,true,true,true,false,false,false,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,true,false,false,false,false,false,true,true,true,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,false,true,false,true,true,true,false,true,true,true,false,false,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,true,true,true,false,true,false,false,true,true,false,false,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,true,true,true,false,false,true,false,false,true,true,true,true,true,true,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,false,true,false,true,false,false,false,false,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
}

func qrTechnicalPROnXBitmap() [][]bool {
	out := make([][]bool, 33)
	for i := range qrBitmapTechnicalPROnX {
		out[i] = qrBitmapTechnicalPROnX[i][:]
	}
	return out
}

var qrBitmapCorporateWebsite = [33][33]bool{
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,false,true,true,true,false,true,true,false,false,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,true,true,false,false,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,true,true,false,true,false,true,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,true,true,false,false,true,true,false,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,false,false,false,true,true,true,false,true,true,false,true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,false,true,false,false,true,false,true,false,false,true,true,true,false,false,false,true,true,true,true,true,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,true,true,false,true,true,false,true,true,false,false,true,true,true,false,true,true,true,false,true,true,false,false,false,false,},
	{false,false,false,false,true,true,false,false,true,true,false,false,true,false,true,true,false,false,true,false,false,true,false,false,false,true,false,false,true,false,false,false,false,},
	{false,false,false,false,false,false,false,true,true,false,true,false,false,true,true,false,false,false,true,true,true,false,true,true,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,true,false,false,false,true,true,false,true,true,false,true,true,true,false,true,false,false,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,true,false,true,true,true,false,false,false,false,true,true,true,true,false,true,true,true,true,false,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,false,false,false,false,true,true,false,false,false,true,false,true,true,true,false,false,true,false,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,true,false,true,true,false,false,false,false,true,true,true,false,true,true,true,true,true,false,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,false,false,true,false,true,false,true,false,true,false,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,true,true,false,false,false,true,true,false,false,false,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,false,true,true,true,true,true,true,true,true,true,true,false,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,false,true,false,false,false,false,false,true,true,false,false,false,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,true,true,true,false,false,false,false,true,false,true,true,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,true,false,true,false,true,true,true,true,true,false,false,true,false,false,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
}

func qrCorporateWebsiteBitmap() [][]bool {
	out := make([][]bool, 33)
	for i := range qrBitmapCorporateWebsite {
		out[i] = qrBitmapCorporateWebsite[i][:]
	}
	return out
}

var qrBitmapCasualInterview = [37][37]bool{
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,false,false,false,true,false,false,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,true,true,false,false,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,false,true,true,true,false,false,true,false,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,false,true,false,true,true,false,false,true,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,true,true,false,false,true,true,true,false,false,true,false,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,true,false,true,false,false,true,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,false,false,true,false,true,false,false,false,false,false,true,true,true,true,true,true,false,true,false,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,true,false,false,false,true,true,true,true,false,true,true,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,true,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,true,true,false,true,true,false,false,false,false,false,},
	{false,false,false,false,true,true,true,false,false,true,false,true,false,false,false,true,true,true,true,false,false,false,false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,false,true,true,false,true,false,true,true,false,true,false,true,false,false,false,true,true,true,false,true,false,false,false,true,false,true,true,false,false,false,false,false,false,},
	{false,false,false,false,true,true,false,false,true,true,false,false,false,true,true,true,false,true,true,true,true,true,true,true,false,false,true,false,false,false,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,true,false,false,false,true,false,false,true,false,false,true,false,true,false,false,false,false,true,true,false,false,true,true,false,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,false,true,false,false,true,true,true,false,false,false,true,false,false,true,false,false,false,false,false,},
	{false,false,false,false,false,true,true,true,false,false,true,false,false,true,true,true,false,false,false,true,false,false,false,true,true,true,false,true,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,true,false,true,false,true,true,false,true,true,false,true,false,true,false,false,true,true,false,true,false,true,true,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,true,false,false,true,true,true,false,false,true,false,false,true,true,false,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,true,true,false,false,false,true,false,true,true,false,true,false,false,false,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,false,false,},
	{false,false,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,true,false,false,false,true,true,true,true,true,true,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,true,true,true,false,true,false,false,false,true,false,false,false,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,false,false,false,true,true,false,true,false,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,false,true,true,false,false,false,true,false,false,false,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,false,true,false,true,false,true,true,true,true,false,false,true,true,true,true,true,false,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,false,true,true,false,true,true,true,true,false,true,false,false,false,true,true,true,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,true,true,false,true,false,false,false,false,true,true,true,false,false,true,false,false,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,true,false,true,false,false,true,false,false,false,false,false,true,false,true,false,false,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,true,false,true,false,true,false,false,false,true,true,true,false,true,true,false,true,false,true,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
}

func qrCasualInterviewBitmap() [][]bool {
	out := make([][]bool, 37)
	for i := range qrBitmapCasualInterview {
		out[i] = qrBitmapCasualInterview[i][:]
	}
	return out
}

