// Code generated by gen qr; DO NOT EDIT.
package img

var QrBitmapTechnicalPROnX = [33][33]bool{
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,false,false,false,false,true,true,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,false,true,true,false,false,false,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,false,false,true,false,false,false,false,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,true,false,true,true,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,true,false,true,true,true,true,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,true,true,false,false,true,true,false,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,false,false,true,true,true,false,false,false,true,false,true,false,false,false,false,false,false,true,false,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,false,true,false,false,false,false,false,true,false,true,true,false,false,true,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,false,true,true,false,false,true,true,false,false,true,true,true,false,false,true,false,false,true,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,false,true,false,false,true,false,true,false,false,true,false,false,false,true,true,true,false,true,false,true,true,false,false,false,false,false,},
	{false,false,false,false,false,true,false,false,false,true,true,true,true,false,false,true,true,false,false,true,false,true,true,false,false,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,false,false,false,false,false,false,true,true,false,true,false,true,true,true,false,false,false,true,false,false,true,false,false,false,false,false,},
	{false,false,false,false,false,false,true,true,false,false,true,false,true,true,false,true,true,false,false,true,false,true,false,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,true,true,false,false,true,true,false,false,false,false,true,false,false,false,true,true,true,false,true,true,false,false,false,false,false,},
	{false,false,false,false,true,true,false,true,true,true,true,false,true,false,true,false,false,true,false,true,true,true,true,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,true,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,false,true,true,true,false,true,true,false,true,false,true,false,true,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,false,false,true,false,true,true,true,false,false,false,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,true,false,false,false,false,false,true,true,true,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,false,true,false,true,true,true,false,true,true,true,false,false,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,true,true,true,false,true,false,false,true,true,false,false,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,true,true,true,false,false,true,false,false,true,true,true,true,true,true,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,false,true,false,true,false,false,false,false,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
}

func QrTechnicalPROnXBitmap() [][]bool {
	out := make([][]bool, 33)
	for i := range QrBitmapTechnicalPROnX {
		out[i] = QrBitmapTechnicalPROnX[i][:]
	}
	return out
}

var QrBitmapCorporateWebsite = [33][33]bool{
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,false,true,true,true,false,true,true,false,false,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,true,true,false,false,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,true,true,false,true,false,true,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,true,true,false,false,true,true,false,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,false,false,false,true,true,true,false,true,true,false,true,true,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,false,true,false,false,true,false,true,false,false,true,true,true,false,false,false,true,true,true,true,true,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,true,true,false,true,true,false,true,true,false,false,true,true,true,false,true,true,true,false,true,true,false,false,false,false,},
	{false,false,false,false,true,true,false,false,true,true,false,false,true,false,true,true,false,false,true,false,false,true,false,false,false,true,false,false,true,false,false,false,false,},
	{false,false,false,false,false,false,false,true,true,false,true,false,false,true,true,false,false,false,true,true,true,false,true,true,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,true,false,false,false,true,true,false,true,true,false,true,true,true,false,true,false,false,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,true,false,true,true,true,false,false,false,false,true,true,true,true,false,true,true,true,true,false,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,false,false,false,false,true,true,false,false,false,true,false,true,true,true,false,false,true,false,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,true,false,true,true,false,false,false,false,true,true,true,false,true,true,true,true,true,false,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,false,false,true,false,true,false,true,false,true,false,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,true,true,false,false,false,true,true,false,false,false,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,false,true,true,true,true,true,true,true,true,true,true,false,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,true,true,false,false,false,false,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,false,true,false,false,false,false,false,true,true,false,false,false,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,true,true,true,false,false,false,false,true,false,true,true,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,true,false,true,false,true,true,true,true,true,false,false,true,false,false,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
}

func QrCorporateWebsiteBitmap() [][]bool {
	out := make([][]bool, 33)
	for i := range QrBitmapCorporateWebsite {
		out[i] = QrBitmapCorporateWebsite[i][:]
	}
	return out
}

var QrBitmapCasualInterview = [37][37]bool{
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,false,false,false,true,false,false,true,true,true,true,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,true,true,false,false,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,false,true,true,true,false,false,true,false,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,false,true,false,true,true,false,false,true,true,false,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,true,true,false,false,true,true,true,false,false,true,false,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,true,false,true,false,false,true,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,false,true,false,true,true,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,false,false,true,false,true,false,false,false,false,false,true,true,true,true,true,true,false,true,false,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,true,false,false,false,true,true,true,true,false,true,true,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,true,false,false,true,true,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,true,true,false,true,true,false,false,false,false,false,},
	{false,false,false,false,true,true,true,false,false,true,false,true,false,false,false,true,true,true,true,false,false,false,false,false,true,true,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,false,true,true,false,true,false,true,true,false,true,false,true,false,false,false,true,true,true,false,true,false,false,false,true,false,true,true,false,false,false,false,false,false,},
	{false,false,false,false,true,true,false,false,true,true,false,false,false,true,true,true,false,true,true,true,true,true,true,true,false,false,true,false,false,false,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,true,false,false,false,true,false,false,true,false,false,true,false,true,false,false,false,false,true,true,false,false,true,true,false,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,false,true,true,true,true,false,true,true,false,true,false,false,true,true,true,false,false,false,true,false,false,true,false,false,false,false,false,},
	{false,false,false,false,false,true,true,true,false,false,true,false,false,true,true,true,false,false,false,true,false,false,false,true,true,true,false,true,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,true,false,true,false,true,true,false,true,true,false,true,false,true,false,false,true,true,false,true,false,true,true,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,true,true,false,false,false,true,true,true,false,false,true,true,true,false,false,true,false,false,true,true,false,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,true,true,false,false,false,true,false,true,true,false,true,false,false,false,true,true,true,false,true,false,false,false,false,false,true,false,false,false,false,false,false,},
	{false,false,false,false,false,true,true,true,true,false,true,true,false,false,true,true,true,true,false,false,false,true,true,true,true,true,true,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,false,true,false,true,true,true,false,true,false,false,false,true,false,false,false,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,false,false,true,true,true,true,false,false,false,false,false,true,true,false,true,false,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,false,false,false,true,true,false,false,false,true,false,false,false,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,false,true,false,true,false,true,true,true,true,false,false,true,true,true,true,true,false,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,false,true,true,false,true,true,true,true,false,true,false,false,false,true,true,true,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,true,true,false,true,false,false,false,false,true,true,true,false,false,true,false,false,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,true,false,true,false,false,true,false,false,false,false,false,true,false,true,false,false,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,true,false,true,false,true,false,false,false,true,true,true,false,true,true,false,true,false,true,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
}

func QrCasualInterviewBitmap() [][]bool {
	out := make([][]bool, 37)
	for i := range QrBitmapCasualInterview {
		out[i] = QrBitmapCasualInterview[i][:]
	}
	return out
}

var QrBitmapMyX = [33][33]bool{
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,false,false,true,false,false,false,true,true,false,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,true,false,false,false,true,false,true,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,false,true,false,false,false,true,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,false,false,true,false,true,true,true,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,true,false,false,true,true,true,true,false,false,true,false,true,true,true,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,false,false,true,true,true,false,false,true,true,false,true,false,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,false,true,false,true,false,true,false,true,false,true,true,true,true,true,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,true,true,true,false,true,true,true,true,true,false,false,false,true,true,false,false,true,true,true,false,false,false,true,false,false,false,false,false,false,},
	{false,false,false,false,false,true,true,false,false,false,false,false,false,true,false,true,true,true,true,false,true,true,true,true,false,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,true,false,true,true,true,true,false,true,false,true,true,true,false,false,false,false,true,false,false,true,false,true,true,true,false,false,false,false,},
	{false,false,false,false,false,true,true,false,true,false,false,false,true,true,true,false,true,true,true,true,true,true,true,true,true,false,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,false,true,true,false,true,true,false,false,true,true,false,true,false,true,true,true,true,true,false,true,false,true,true,false,false,false,false,},
	{false,false,false,false,false,true,false,false,true,false,false,true,true,true,true,true,false,true,true,false,true,true,true,false,false,true,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,true,false,true,false,true,true,false,true,false,false,false,true,true,false,false,false,true,true,false,false,true,true,true,false,false,false,false,},
	{false,false,false,false,false,true,true,false,true,false,false,true,false,false,true,true,false,true,false,false,true,false,true,false,true,false,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,true,false,true,true,true,true,false,false,false,false,true,true,false,true,true,true,true,true,true,true,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,true,true,false,true,true,false,false,false,true,true,false,true,true,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,true,true,true,false,true,true,true,false,true,false,true,true,false,true,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,false,true,false,true,true,true,true,true,false,false,false,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,true,true,true,true,true,false,false,true,true,true,true,true,true,false,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,false,false,false,true,false,true,true,false,false,false,false,true,true,true,true,false,false,false,false,false,false,},
	{false,false,false,false,true,false,true,true,true,false,true,false,true,false,false,false,false,false,true,true,false,false,false,false,true,false,false,false,true,false,false,false,false,},
	{false,false,false,false,true,false,false,false,false,false,true,false,true,true,true,true,false,true,false,true,true,false,true,false,true,true,false,true,false,false,false,false,false,},
	{false,false,false,false,true,true,true,true,true,true,true,false,true,true,true,false,true,true,false,true,true,true,false,true,false,false,false,true,true,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
	{false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,},
}

func QrMyXBitmap() [][]bool {
	out := make([][]bool, 33)
	for i := range QrBitmapMyX {
		out[i] = QrBitmapMyX[i][:]
	}
	return out
}

